<a href="https://colab.research.google.com/github/Minh-A/Pytorch_DeepLearning/blob/main/Pytorch_book.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1월 4일: 책 5강

In [ ]:
# 파이토치 라이브러리 임포트
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# sklearn 라이브러리 임포트
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

# pandas 라이브러리 임포트
import pandas as pd

In [ ]:
wine = load_wine()
wine

{'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:           

In [ ]:
pd.DataFrame(wine.data, columns= wine.feature_names)

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0      14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1      13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2      13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3      14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4      13.24        2.59  2.87  ...  1.04                          2.93    735.0
..       ...         ...   ...  ...   ...                           ...      ...
173    13.71        5.65  2.45  ...  0.64                          1.74    740.0
174    13.40        3.91  2.48  ...  0.70                          1.56    750.0
175    13.27        4.28  2.26  ...  0.59                          1.56    835.0
176    13.17        2.59  2.37  ...  0.60                          1.62    840.0
177    14.13        4.10  2.74  ...  0.61                          1.60    560.0

[178 rows x 13 columns]

In [ ]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [ ]:
wine_data = wine.data[0:130]
wine_target = wine.target[0:130]

In [ ]:
train_x, test_x, train_y, test_y = train_test_split(wine_data, wine_target, test_size = 0.2)

print(len(train_x))
print(len(test_x))

104
26


In [ ]:
train_x = torch.from_numpy(train_x).float()
train_y = torch.from_numpy(train_y).long()

test_x = torch.from_numpy(test_x).float()
test_y = torch.from_numpy(test_y).long()

print(train_x.shape)
print(train_y.shape)

torch.Size([104, 13])
torch.Size([104])


> Numpy 배열을 텐서로 변환
* torch.from_numpy()

> 변수들의 합쳐서 하나의 데이터 집합을 생성
* TensorDataset()

> 데이터 집합을 미니배치로 나누어
* DataLoader()

In [ ]:
train = TensorDataset(train_x, train_y)

print(train[0])

# 미니배치로 분할
train_loader = DataLoader(train, batch_size=16, shuffle=True)

(tensor([1.3290e+01, 1.9700e+00, 2.6800e+00, 1.6800e+01, 1.0200e+02, 3.0000e+00,
        3.2300e+00, 3.1000e-01, 1.6600e+00, 6.0000e+00, 1.0700e+00, 2.8400e+00,
        1.2700e+03]), tensor(0))


In [ ]:
for i,b in train_loader:
  print(b)

  # 임마가 배치사이즈 16개
  # 전체 텐서는 7개

tensor([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1])
tensor([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])
tensor([0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1])
tensor([1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1])
tensor([0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1])
tensor([1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0])
tensor([1, 1, 0, 1, 1, 0, 0, 0])


In [ ]:
# 신경망 구성
class Net(nn.Module):
  def __init__(self):
    super(Net,self).__init__()
    self.fc1 = nn.Linear(13,96)
    self.fc2 = nn.Linear(96,2)

  def forward(self,x):
    x = F.relu(self.fc1(x))
    x = self.fc2(x)
    return F.log_softmax(x)

# 인스턴스 생성
model = Net()

> 초기 모듈을 생성
* nn.Modeule

> 층 (선형변환)
* nn.Linear()    여기에 bias도 들어간다잉

> 활성화 함수 (앞의 F는 functional의 약자)
* F.relu()     : Relu함수
* F.log_softmax   : 로그소프트맥스 함수

> 크로스엔트로피 설명
* https://hyunw.kim/blog/2017/10/26/Cross_Entropy.html

In [ ]:
# 모형 학습

# 오차함수 객체
criterion = nn.CrossEntropyLoss()

# 최적화 담당
optimizer = optim.SGD(model.parameters(), lr = 0.01)  #경사하강법은 SGD

# 학습시작
for epoch in range(300):
  total_loss = 0

  for train_x, train_y in train_loader:
    # train_x, train_y = Variable(train_x), Variable(train_y)  #이거만다 사용하너

    optimizer.zero_grad()  # 경사초기화

    output = model(train_x)  # 순전파 계산

    loss = criterion(output, train_y)  # 오차 계산
    loss.backward()  # 역전파 계산

    optimizer.step()  #가중치 업데이트

    total_loss += loss.data  # 누적오차 계산
  
  if (epoch+1) % 50 == 0:
    print(epoch+1, float(total_loss))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  # This is added back by InteractiveShellApp.init_path()


50 4.787615776062012
100 4.797826290130615
150 4.849554061889648
200 4.814967155456543
250 4.765681266784668
300 4.781067371368408


> 오차 함수
* nn.CrossEntropyLoss()  # 크로스엔트로피

> 경사하강법으로 최적화
* optim.SGD(model.parameters(), lr = 0.01)

> 래핑과 계산과정 기록 -- 먼데이거
* Variable()

> 경사의 합을 구함
* backward()

In [ ]:
test_x, test_y = Variable(test_x), Variable(test_y)   # 이거 안해도 문제 없움

# 출력이 0또는 1이 되도록
result = torch.max(model(test_x).data, 1)[1]

# 측정
accuracy = sum(test_y.data.numpy() == result.numpy()) / len(test_y.data.numpy())
accuracy

# 임마는 그냥 최닷값을 뽑아서 1을 넣어주는데 아리송송해

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  # This is added back by InteractiveShellApp.init_path()


0.46153846153846156

> 최댓값 반환
* torch.max()

In [ ]:
torch.max(model(test_x).data, 1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  # This is added back by InteractiveShellApp.init_path()


torch.return_types.max(values=tensor([-0.5648, -0.5648, -0.5648, -0.5648, -0.5648, -0.5648, -0.5648, -0.5648,
        -0.5648, -0.5648, -0.5648, -0.5648, -0.5648, -0.5648, -0.5648, -0.5648,
        -0.5648, -0.5648, -0.5648, -0.5648, -0.5648, -0.5648, -0.5648, -0.5648,
        -0.5648, -0.5648]), indices=tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1]))

In [ ]:
model(test_x).data

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  # This is added back by InteractiveShellApp.init_path()


tensor([[-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648],
        [-0.8404, -0.5648]])